### ISSUE TITLE
AttributeError: 'Vector' object has no attribute 'orthogonal'

### ISSUE THREAD

**Issue by tocs** [meshulam/sly#2]
I got all the dependencies installed and ran the metropol example and got an error.

Traceback (most recent call last):
  File "/home/lotsofdirstuff/sly/sly/examples/metropol.blend/metropol.py.001", line 59, in <module>
  File "/home/lotsofdirstuff/sly/sly/ops.py", line 10, in border
    cuts = [cut.overlap_poly() for cut in sli.cuts]
  File "/home/lotsofdirstuff/sly/sly/ops.py", line 10, in <listcomp>
    cuts = [cut.overlap_poly() for cut in sli.cuts]
  File "/home/lotsofdirstuff/sly/sly/slicer.py", line 162, in overlap_poly

AttributeError: 'Vector' object has no attribute 'orthogonal'
Error: Python script fail, look in the console for now...

I am still learning where everything is and what every thing does. Maybe I can find where I went wrong.

**Comment by meshulam** [comment]
The vector object in that line is a mathutils Vector, which is part of the Blender lib: http://www.blender.org/api/blender_python_api_2_73_release/mathutils.html#mathutils.Vector.orthogonal

What version of blender are you running? Maybe 'orthogonal' is a relatively new addition to the API. You might also want to try calling orthogonal() from the blender console, like:

```
from mathutils import Vector
vec = Vector((1, 0, 0))
vec.orthogonal()
```

If that works, I'll need to dig in more.

**Comment by tocs** [comment]
I have been running blender 2.69 and Vectors do not have an orthogonal method.
For what it it worth it looks like Blender 2.71 first had an orthogonal method.

I am planning on upgrading my Blender to 2.74 and trying again.
Thanks for the help.

**Comment by meshulam** [comment]
Cool, I've updated the Readme stating that Blender 2.71 or greater is required. If you get it working, can you close this issue? Thanks!
